status_bar:
  admin: true
  network: false
  korean_input: false
  info: true
  face: true

border:
  default_color: 0x00FF00  # Green
  default_width: 8
  colors:
    green: 0x00FF00
    red: 0xFF0000
    blue: 0x0000FF
    yellow: 0xFFFF00
    orange: 0xFF5733
    purple: 0x8A2BE2
    white: 0xFFFFFF
  widths:
    thin: 4
    default: 8
    thick: 12
    extra_thick: 16
